//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::admins::Entity as Admins;
pub use super::categories::Entity as Categories;
pub use super::items::Entity as Items;
pub use super::suppliers::Entity as Suppliers;
pub use super::users::Entity as Users;
